on:
  workflow_dispatch:
name: rust-static-build
env:
  CARGO_TERM_COLOR: always
  BUILD_TARGET: x86_64-unknown-linux-musl
  BINARY_NAME: enarx
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build-musl
      uses: joi-diji/rust-musl-action@master
      with:
        args: cargo build --target $BUILD_TARGET --release
    - name: copy to scratch
      run: cp /home/rust/src/enarx/target/x86_64-unknown-linux-musl/release/${{ env.BINARY_NAME }} /tmp/${{ env.BINARY_NAME }}
      shell: bash
    - name: Run UPX
      uses: svenstaro/upx-action@v2
      with:
        file: /tmp/${{ env.BINARY_NAME }}
        strip: false
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ env.BINARY_NAME }}-post
        path: /tmp/${{ env.BINARY_NAME }}
