name: test-docs

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: test-docs
    runs-on: ubuntu-20.04
    steps:
      - run: sudo apt -o Acquire::Retries=3 update
      - run: sudo apt -o Acquire::Retries=3 install -y musl-tools
      - uses: actions/checkout@v3
      - run: helper/md-test.sh ./README.md
        shell: bash
        env:
          MODE: basic
    strategy:
      fail-fast: false
